import { FileText, Download, Calendar, ChevronRight } from 'lucide-react';
import Button from '../components/shared/Button';
import Badge from '../components/shared/Badge';
import { api } from '../lib/api';

const reports = [
  {
    id: 'rpt-004',
    title: 'Weekly AI CEO Report',
    subtitle: 'Week 48 — Nov 24–30, 2025',
    status: 'ready' as const,
    description: 'Revenue grew 12.3% WoW. Churn dropped to 3.1%. 5 critical insights flagged.',
    date: 'Dec 1, 2025',
  },
  {
    id: 'rpt-003',
    title: 'Weekly AI CEO Report',
    subtitle: 'Week 47 — Nov 17–23, 2025',
    status: 'ready' as const,
    description: 'Revenue up 8.7%. Chennai region recovery noted. 2 onboarding bottlenecks resolved.',
    date: 'Nov 24, 2025',
  },
  {
    id: 'rpt-002',
    title: 'Weekly AI CEO Report',
    subtitle: 'Week 46 — Nov 10–16, 2025',
    status: 'ready' as const,
    description: 'Flat revenue week. Churn spike in APAC detected. New expansion pipeline +$45K.',
    date: 'Nov 17, 2025',
  },
  {
    id: 'rpt-001',
    title: 'Monthly AI CEO Report',
    subtitle: 'October 2025',
    status: 'ready' as const,
    description: 'Full monthly review. Q4 forecast on track. 3 new enterprise accounts closed.',
    date: 'Nov 3, 2025',
  },
];

const statusMeta = {
  ready: { label: 'Ready', variant: 'success' as const },
  generating: { label: 'Generating', variant: 'warning' as const },
  failed: { label: 'Failed', variant: 'critical' as const },
};

export default function Reports() {
  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-xl font-semibold font-heading text-foreground">
            Reports
          </h1>
          <p className="text-sm text-foreground-secondary mt-1">
            Weekly and monthly reports generated by your AI CEO.
          </p>
        </div>
        <Button variant="primary" size="sm" onClick={() => window.open(api.weeklyReportPdfUrl(), '_blank')}>
          <Download className="w-4 h-4" />
          Generate Now
        </Button>
      </div>

      {/* Subscription info */}
      <div className="bg-background-card border border-border rounded-xl p-5">
        <div className="flex items-center gap-3 mb-3">
          <Calendar className="w-5 h-5 text-primary" />
          <span className="text-sm font-semibold text-foreground font-heading">
            Automatic Reports
          </span>
        </div>
        <p className="text-sm text-foreground-secondary">
          Weekly reports are generated every Monday at 9 AM and delivered via Slack to{' '}
          <span className="text-foreground font-medium">#ai-weekly-report</span>. Monthly
          reports land on the 1st of each month. You can also generate a report on demand.
        </p>
      </div>

      {/* Report list */}
      <div>
        <h2 className="text-base font-semibold font-heading text-foreground mb-4">
          Recent Reports
        </h2>
        <div className="space-y-3">
          {reports.map((rpt) => (
            <div
              key={rpt.id}
              className="bg-background-card border border-border rounded-xl p-4 flex flex-col sm:flex-row sm:items-center gap-4 hover:border-border-strong transition-colors duration-200 cursor-pointer"
            >
              <div className="flex items-center gap-3 flex-1 min-w-0">
                <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                  <FileText className="w-5 h-5 text-primary" />
                </div>
                <div>
                  <div className="flex items-center gap-2 mb-0.5">
                    <p className="text-sm font-semibold text-foreground font-heading">
                      {rpt.title}
                    </p>
                    <Badge
                      label={statusMeta[rpt.status].label}
                      variant={statusMeta[rpt.status].variant}
                    />
                  </div>
                  <p className="text-xs text-foreground-secondary">
                    {rpt.subtitle} — {rpt.date}
                  </p>
                  <p className="text-sm text-foreground-secondary mt-1.5 line-clamp-2">
                    {rpt.description}
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-2 shrink-0">
                <Button
                  variant="secondary"
                  size="sm"
                  onClick={rpt.id === 'rpt-004' ? () => window.open(api.weeklyReportPdfUrl(), '_blank') : undefined}
                >
                  <Download className="w-4 h-4" />
                  PDF
                </Button>
                <ChevronRight className="w-4 h-4 text-foreground-secondary" />
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Empty state for when no reports exist */}
      {reports.length === 0 && (
        <div className="bg-background-card border border-border rounded-xl p-12 text-center">
          <FileText className="w-10 h-10 text-foreground-secondary mx-auto mb-4" />
          <p className="text-base font-semibold text-foreground mb-1 font-heading">
            No reports yet
          </p>
          <p className="text-sm text-foreground-secondary mb-6">
            Your first weekly report is generated automatically, or you can create one now.
          </p>
          <Button variant="primary" size="md">
            <Download className="w-4 h-4" />
            Generate First Report
          </Button>
        </div>
      )}
    </div>
  );
}
